apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: memcached
    deployment-copier: "yes"
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - image: memcached
        name: memcached
